export enum HobbyOptions {
  Reading = 'Reading',
  PlayingGuitar = 'Playing Guitar',
  Collecting = 'Collecting',
  CampingOrBackpacking = 'Camping/Backpacking',
  Hunting = 'Hunting',
  Fishing = 'Fishing',
  ModelBuilding = 'Model Building',
  LeatherWorking = 'Leather Working',
  Archey = 'Archey',
  LetterWriting = 'Letter Writing',
  Hiking = 'Hiking',
  Photography = 'Photography',
  Cooking = 'Cooking',
  Blacksmithing = 'Blacksmithing',
  Blogging = 'Blogging',
  Paintball = 'Paintball',
  DrawingAndPainting = 'Drawing and Painting',
  Knitting = 'Knitting',
  ComputerProgramming = 'Computer Programming',
  AmateurAstronomy = 'Amateur Astronomy',
  Marksmanship = 'Marksmanship',
  Gardening = 'Gardening',
  Woodcrafting = 'Woodcrafting',
  FoodStyling = 'Food Styling',
  Dancing = 'Dancing'
}
